baseurl = "https://barloweanalytics.com/"
languageCode = "en-us"
theme = "hugo-theme-terminal"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "pink"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 6
  # set theme to full screen width
  fullWidthTheme = false
  # center theme with default width
  centerTheme = false
  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = "matthew_barlowe"
  site = "barloweanalytic"

[languages]
  [languages.en]
    title = "Barlowe Analytics"
    subtitle = "Posts about Data Science"
    keywords = ""
    copyright = "2019 Barlowe Analytics"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    googleAnalytics = "UA-138686262-1"

    [languages.en.params.logo]
      logoText = "Barlowe Analytics"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/aboutme"
      [[languages.en.menu.main]]
        identifier = "work"
        name = "Work"
        url = "/work"
      [[languages.en.menu.main]]
        identifier = "Tutorials"
        name = "Tutorials"
        url = "/tutorials"
      [[languages.en.menu.main]]
        identifier = "Projects"
        name = "Projects"
        url = "/projects"

[deployment]

[[deployment.targets]]
name = "barloweanalytics.com"
url = "s3://barloweanalytics.com"

cloudFrontDistributionID = "E2AV6QX834HOND"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
